from tkinter import *
from tkinter import ttk
from Operaciones import operaciones

class Interfaz:
    def __init__(self, ventana):
        self.ventana = ventana
        operacion = operaciones(self)
        self.frame = ttk.Frame(ventana)
        self.frame.grid(column=0, row=0)
        self.entrada = ttk.Entry(self.frame)
        self.entrada.grid(column=0, row=0, columnspan=4, sticky=(W, E))
        self.botonC = ttk.Button(self.frame, text="C", command=lambda: operacion.borrarC())
        self.botonC.grid(column=0, row=2, columnspan=2, sticky=(W, E))
        self.botonB = ttk.Button(self.frame, text=chr(9003), command=lambda: operacion.borrar())
        self.botonB.grid(column=2, row=2, columnspan=2, sticky=(W, E))
        self.botonAP = ttk.Button(self.frame, text="(", command=lambda: operacion.click("("))
        self.botonAP.grid(column=0, row=3)
        self.botonCP = ttk.Button(self.frame, text=")", command=lambda: operacion.click(")"))
        self.botonCP.grid(column=1, row=3)
        self.botonP = ttk.Button(self.frame, text=".", command=lambda: operacion.click("."))
        self.botonP.grid(column=2, row=3)
        self.botonD = ttk.Button(self.frame, text=chr(247), command=lambda: operacion.click("/"))
        self.botonD.grid(column=3, row=3)
        self.boton7 = ttk.Button(self.frame, text="7", command=lambda: operacion.click(7))
        self.boton7.grid(column=0, row=4)
        self.boton8 = ttk.Button(self.frame, text="8", command=lambda: operacion.click(8))
        self.boton8.grid(column=1, row=4)
        self.boton9 = ttk.Button(self.frame, text="9", command=lambda: operacion.click(9))
        self.boton9.grid(column=2, row=4)
        self.botonM = ttk.Button(self.frame, text="x", command=lambda: operacion.click("*"))
        self.botonM.grid(column=3, row=4)
        self.boton4 = ttk.Button(self.frame, text="4", command=lambda: operacion.click(4))
        self.boton4.grid(column=0, row=5)
        self.boton5 = ttk.Button(self.frame, text="5", command=lambda: operacion.click(5))
        self.boton5.grid(column=1, row=5)
        self.boton6 = ttk.Button(self.frame, text="6", command=lambda: operacion.click(6))
        self.boton6.grid(column=2, row=5)
        self.botonR = ttk.Button(self.frame, text="-", command=lambda: operacion.click("-"))
        self.botonR.grid(column=3, row=5)
        self.boton1 = ttk.Button(self.frame, text="1", command=lambda: operacion.click(1))
        self.boton1.grid(column=0, row=6)
        self.boton2 = ttk.Button(self.frame, text="2", command=lambda: operacion.click(2))
        self.boton2.grid(column=1, row=6)
        self.boton3 = ttk.Button(self.frame, text="3", command=lambda: operacion.click(3))
        self.boton3.grid(column=2, row=6)
        self.botonS = ttk.Button(self.frame, text="+", command=lambda: operacion.click("+"))
        self.botonS.grid(column=3, row=6)
        self.boton0 = ttk.Button(self.frame, text="0", command=lambda: operacion.click(0))
        self.boton0.grid(column=0, row=7, columnspan=2, sticky=(W, E))
        self.botonI = ttk.Button(self.frame, text="=", command=lambda: operacion.operacion())
        self.botonI.grid(column=2, row=7, columnspan=2, sticky=(W, E))

def main():
    ventana = Tk()
    ventana.title("Calculadora-RBEE")
    ventana.columnconfigure(0, weight=1)
    ventana.rowconfigure(0, weight=1)
    ventana.resizable(0,0)
    app = Interfaz(ventana)
    ventana.mainloop()

main()